name: Codecov Coverage Upload

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        env:
          API_URL: 'https://jsonplaceholder.typicode.com'
        with:
          REACT_APP_BASE_URL: ${{env.API_URL}}
      - run: yarn test:coverage
#      - uses: codecov/codecov-action@v1
